### ISSUE TITLE
Chapter 2 tests no change (just Github token updated) 22 passed but 2 tests failed.

### ISSUE THREAD

**Issue by aozturk** [AndrewKeig/advanced-express-application-development#1]
22 passing (3s)
  2 failing

  1) vision github api when requesting an available resource /project/:id/commits should respond with 200:
     Uncaught TypeError: Cannot convert null to object
      at hasOwnProperty (native)
      at Function._.has (/Users/aozturk/Development/advanced-express-web-application-development/chapter-2/node_modules/underscore/underscore.js:995:27)
      at /Users/aozturk/Development/advanced-express-web-application-development/chapter-2/test/github.js:73:20
      at Test.assert (/Users/aozturk/Development/advanced-express-web-application-development/chapter-2/node_modules/supertest/lib/test.js:190:3)
      at /Users/aozturk/Development/advanced-express-web-application-development/chapter-2/node_modules/supertest/lib/test.js:119:10
      at Test.Request.callback (/Users/aozturk/Development/advanced-express-web-application-development/chapter-2/node_modules/supertest/node_modules/superagent/lib/node/index.js:573:30)
      at Test.<anonymous> (/Users/aozturk/Development/advanced-express-web-application-development/chapter-2/node_modules/supertest/node_modules/superagent/lib/node/index.js:133:10)
      at Test.EventEmitter.emit (events.js:95:17)
      at IncomingMessage.<anonymous> (/Users/aozturk/Development/advanced-express-web-application-development/chapter-2/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:12)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickCallback (node.js:415:13)

  2) vision github api when requesting an available resource /project/:id/issues should respond with 200:
     Uncaught TypeError: Cannot convert null to object
      at hasOwnProperty (native)
      at Function._.has (/Users/aozturk/Development/advanced-express-web-application-development/chapter-2/node_modules/underscore/underscore.js:995:27)
      at /Users/aozturk/Development/advanced-express-web-application-development/chapter-2/test/github.js:111:20
      at Test.assert (/Users/aozturk/Development/advanced-express-web-application-development/chapter-2/node_modules/supertest/lib/test.js:190:3)
      at /Users/aozturk/Development/advanced-express-web-application-development/chapter-2/node_modules/supertest/lib/test.js:119:10
      at Test.Request.callback (/Users/aozturk/Development/advanced-express-web-application-development/chapter-2/node_modules/supertest/node_modules/superagent/lib/node/index.js:573:30)
      at Test.<anonymous> (/Users/aozturk/Development/advanced-express-web-application-development/chapter-2/node_modules/supertest/node_modules/superagent/lib/node/index.js:133:10)
      at Test.EventEmitter.emit (events.js:95:17)
      at IncomingMessage.<anonymous> (/Users/aozturk/Development/advanced-express-web-application-development/chapter-2/node_modules/supertest/node_modules/superagent/lib/node/index.js:703:12)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickCallback (node.js:415:13)

**Comment by AndrewKeig** [comment]
Hey apologise; for some reason I have not been receiving comms from this repo.

Did you manage to resolve this?
